import type { Metadata } from "next";
import "../assets/styles/globals.css";
import Header from "../components/header";
import Note from "../components/note";
import { NextAuthProvider } from "./providers";

export const metadata: Metadata = {
  title: "Tarefas+ | Organize suas tarefas de forma simples e eficiente",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className="bg-[#0F0F0F] flex flex-col w-full min-h-[100vh] items-center justify-center">
        <NextAuthProvider>
          <Header />
          {children}
          <Note
            loggedIn={false}
          />
        </NextAuthProvider>
      </body>
    </html>
  );
}
